### ISSUE TITLE
Add description to scripts

### ISSUE THREAD

**Issue by ChappIO** [ScriptinatorIO/script-service#13]
Only a name leaves very little room for expression. A description field would be nice.

I'm thinking: freeform string up to 100 characters long?

```
A hundred characters leaves quite some room for verbose expression like this one... It fits!
```

**Comment by LucaScorpion** [comment]
Absolutely! I'm already working on a branch (`cleanup`) where I've added this, so it's WIP :)

**Comment by ChappIO** [comment]
Sweet.
